version: '2'

services:
  redis-sentinel:
    image: anyili/bitnami-redismod-sentinel:latest
    volumes:
      - redis-sentinel_data:/bitnami
  redis:
    image: anyili/bitnami-redismod:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/bitnami
volumes:
  redis-sentinel_data:
    driver: local
  redis_data:
    driver: local
